# Generated by Django 5.2 on 2025-07-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttest', '0003_remove_test_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='in_progress', max_length=20),
        ),
    ]
