# Generated by Django 5.2 on 2025-08-06 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttest', '0008_alter_testattempt_test'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='testattempt',
            old_name='feedback_generated',
            new_name='is_practice',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='is_dynamic',
        ),
        migrations.AddField(
            model_name='testattempt',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (applies only to formal tests)', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='level',
            field=models.CharField(choices=[('basic', 'Basic'), ('medium', 'Medium'), ('hard', 'Hard')], help_text='Level of the questions in this test', max_length=10),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smarttest.test'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smarttest.topic'),
        ),
    ]
