# Generated by Django 5.2 on 2025-07-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ai_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
