# Generated by Django 5.2 on 2025-07-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarttest', '0002_answer_ai_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='description',
        ),
    ]
