# Generated by Django 5.2 on 2025-07-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttest', '0004_testattempt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Correct answer for the question', null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='feedback_generated',
            field=models.BooleanField(default=False),
        ),
    ]
