# Generated by Django 5.2 on 2025-08-06 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttest', '0007_testattempt_is_dynamic_testattempt_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='smarttest.test'),
        ),
    ]
