# Generated by Django 5.2 on 2025-08-16 19:36
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('smarttest', '0009_rename_feedback_generated_testattempt_is_practice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='title',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
    ]
