# Generated by Django 5.2 on 2025-08-19 19:57

from django.db import migrations
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('smarttest', '0012_add_level_to_testattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='started_at',
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
                db_column='started_at'
            ),
        ),
    ]
