# Generated by Django 5.2 on 2025-08-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttest', '0013_add_started_at_to_testattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='completed_at',
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
                db_column='completed_at'
            ),
        ),
    ]
