# Generated by Django 5.2 on 2025-08-27 18:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_course_topics'),
        ('smarttest', '0015_populate_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='topic',
        ),
        migrations.AddField(
            model_name='test',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='main.course'),
        ),
        migrations.AddField(
            model_name='test',
            name='is_practice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.PositiveIntegerField(default=20, help_text='Time limit in minutes'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, default=20, help_text='Time limit in minutes (applies to both practice and formal tests)'),
        ),
    ]
