# Generated by Django 5.2 on 2025-05-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_category_title_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='certificate_issued',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='completed',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('certified', 'Certified')], default='in_progress', max_length=20),
        ),
    ]
