# Generated by Django 5.2 on 2025-05-22 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_course_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='recommended_hours_per_week',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='Recommended study hours per week(generally 5 hour)', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Duration in hours', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
