# Generated by Django 5.2 on 2025-05-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_course_recommended_hours_per_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('nepali', 'Nepali'), ('sanskrit', 'Sanskrit'), ('maithili', 'Maithili'), ('hindi', 'Hindi'), ('nepenglish', 'NepEnglish')], default='english', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='total_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='video',
            field=models.FileField(blank=True, help_text='Upload section video file', null=True, upload_to='section_videos/%Y/%m/%d/'),
        ),
    ]
