# Generated by Django 5.2 on 2025-05-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_course_average_rating_course_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True, default='Students will learn the skills and knowledge related to this course', help_text='What students will learn (one per line or bullet points)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, default='No specific requirements', help_text='What students should know before taking this course (one per line or bullet points)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, default='Syllabus will be provided in the course', help_text='Course outline or weekly/module-based syllabus (one topic per line)', null=True),
        ),
    ]
