# Generated by Django 5.2 on 2025-05-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_course_learning_outcomes_course_requirements_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
