# Generated by Django 5.2 on 2025-06-06 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_progresses', to='main.enrollment')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='main.section')),
            ],
            options={
                'verbose_name': 'Section Progress',
                'verbose_name_plural': 'Section Progresses',
                'db_table': 'section_progress',
                'unique_together': {('enrollment', 'section')},
            },
        ),
    ]
