# Generated by Django 5.2 on 2025-06-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sectionprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionprogress',
            old_name='watched_at',
            new_name='started_at',
        ),
    ]
