# Generated by Django 5.2 on 2025-06-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_watched_at_sectionprogress_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='keywords',
            field=models.CharField(blank=True, help_text='Separate Keywords with commas (e.g., Python, Django, Web Development) for recommendation', max_length=200, null=True),
        ),
    ]
