# Generated by Django 5.2 on 2025-06-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_course_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_sections',
            field=models.ManyToManyField(to='main.section'),
        ),
    ]
