# Generated by Django 5.2 on 2025-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_enrollment_completed_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='completed_sections',
        ),
        migrations.AddField(
            model_name='sectionprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionprogress',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
