# Generated by Django 5.2 on 2025-06-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_enrollment_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(upload_to='certificates/%Y/%m/%d/'),
        ),
    ]
