# Generated by Django 5.2 on 2025-06-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_attachment_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_at']},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='updated_at',
        ),
    ]
