# Generated by Django 5.2 on 2025-06-26 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(limit_choices_to={'status': 'completed'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='main.enrollment'),
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='course',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='student',
        ),
    ]
