# Generated by Django 5.2 on 2025-07-01 21:24

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_certificate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='course',
            index=django.contrib.postgres.indexes.GinIndex(fields=['keywords'], name='keywords_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
