# Generated by Django 5.2 on 2025-07-22 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_course_title_trgm_course_keywords_trgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='video',
            field=models.FileField(blank=True, help_text='Only MP4 video files are allowed', null=True, upload_to='section_videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
