# Generated by Django 5.2 on 2025-08-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_review_rating'),
        ('smarttest', '0015_populate_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='courses', to='smarttest.topic'),
        ),
    ]
