# Generated by Django 5.2 on 2025-09-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_course_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_test_required',
            field=models.BooleanField(default=True),
        ),
    ]
