# Generated by Django 5.2 on 2025-09-07 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_course_is_test_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, help_text='Optional detailed feedback', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')]),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['course', 'created_at'], name='review_course__403a63_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['student', 'course'], name='review_student_0a9824_idx'),
        ),
    ]
