# Generated by Django 5.2 on 2025-06-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_remove_payment_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'eSewa'), ('manual', 'Manual')], default='khalti', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(help_text='Amount in paisa (e.g., 1 Rs = 100 paisa)'),
        ),
    ]
