# Generated by Django 5.2 on 2025-06-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_payment_gateway_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purchase_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
