# Generated by Django 5.2 on 2025-05-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_image_public_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/user_default.png', null=True, upload_to='profile_images/%Y/%m/%d/'),
        ),
    ]
