# Generated by Django 5.2 on 2025-05-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraccount_profile_image_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
